# Model hyperparameters
vocab_size: 10000
context_length: 1024
d_model: 1600
num_layers: 48
num_heads: 25
d_ff: 6400
rope_theta: 10000.0

# Benchmarking parameters
batch_size: 4
warmup_steps: 5
benchmark_steps: 10
forward_only: True
device: "cuda" 
autocast: false