# Model hyperparameters
vocab_size: 10000
context_length: 128
d_model: 1280
num_layers: 36
num_heads: 20
d_ff: 5120
rope_theta: 10000.0

# Benchmarking parameters
batch_size: 32
warmup_steps: 5
benchmark_steps: 20
forward_only: true
device: "cuda" 
autocast: false