# Model hyperparameters
vocab_size: 10000
context_length: 128
d_model: 1024
num_layers: 24
num_heads: 16
d_ff: 4096
rope_theta: 10000.0

# Benchmarking parameters
batch_size: 32
warmup_steps: 5
benchmark_steps: 20
forward_only: false
device: "cuda" 
autocast: false